<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Mađarski glagoli</title>
        <style type="text/css">
            table {color:white;text-align:center;font-size:32pt;}
        </style>
    </head>
    <body>
        <table bgcolor="red" width="100%" height="130">
            <tr>
                <td align="center" font="32">Igeragozó</td>
            </tr>
        </table>   
    </body>
</html>
